# Generated by Django 5.1.7 on 2025-03-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='med',
            old_name='generic_name',
            new_name='batchNumber',
        ),
        migrations.RenameField(
            model_name='med',
            old_name='manufacture',
            new_name='genericName',
        ),
        migrations.RenameField(
            model_name='med',
            old_name='photo',
            new_name='image',
        ),
        migrations.AddField(
            model_name='med',
            name='manufacturer',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
    ]
