# Generated by Django 5.1.7 on 2025-03-24 11:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0002_rename_generic_name_med_batchnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='med',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
