# Generated by Django 5.1.7 on 2025-03-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0003_alter_med_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='med',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
