# Generated by Django 5.1.7 on 2025-03-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0004_med_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='med',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
